#!/bin/bash
# automatically change configuration of Mac OS  based on location
# author: phpluo<phpluo@gmail.com>
# version: 0.1.0

# 指定要连接的 Wi-Fi 名称和位置名称
wifi_name="xhhd888_5G_"
LOCATION_OFFICE="office" #公司的位置
LOCATION_OTHER="other" #其他的位置 公司之外

# 获取当前连接的 Wi-Fi 名称
current_wifi=$(networksetup -getairportnetwork en0 | awk '{print $4}')

# 获取当前网络位置名称
current_location=$(networksetup -getcurrentlocation)

# 如果当前连接的 Wi-Fi 名称与指定的名称相同，并且当前位置不是指定的位置，则修改位置
if [[ "$current_wifi" == "$wifi_name" && "$current_location" != "$LOCATION_OFFICE" ]]
then
    networksetup -switchtolocation "$LOCATION_OFFICE"
    echo "网络位置已更改为 $LOCATION_OFFICE"
  # 发送通知
  osascript -e 'display notification "当前WIFI为 '$current_wifi'，网络位置为 '$LOCATION_OFFICE'" with title "网络位置已更新为办公"'
fi

# # WIFI不是办公室  则修改位置为自动
if [[ "$current_wifi" != "$wifi_name" ]]; then
    networksetup -switchtolocation "$LOCATION_OTHER"
    echo "网络位置已更改为 其他[$current_location]"
    osascript -e 'display notification "当前'$current_location'WIFI为 '$current_wifi'，网络为其他" with title "'$current_location'网络位置已修改为其他"'
fi

